# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.2
  hooks:
    - id: ruff
      args:
        - --fix
      stages: ["push"]
    - id: ruff-format

- repo: local
  hooks:
    - id: Pyright
      name: Pyright
      entry: pyright
      always_run: true
      language: system
      pass_filenames: false
      stages: ["push"]
